import { Disclosure, Tab } from "@headlessui/react";
import { MinusSmallIcon, PlusSmallIcon } from "@heroicons/react/24/outline";

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(" ");
}

const generals = [
  {
    question: "What is DeFiMatrix?",
    answer:
      "DeFiMatrix is an AI-powered yield optimization platform that automatically manages your crypto assets across 50+ vetted protocols. Our autonomous agent handles allocations, compounding, and risk adjustments, delivering institutional-grade strategies with one-click simplicity.",
  },
  {
    question: "How does DeFiMatrix work?",
    answer:
      "Deposit → Connect your wallet (non-custodial), Select → Choose an AI strategy or set custom goals, Earn → Watch your yields grow with autonomous management",
  },
  {
    question: "Is DeFiMatrix secure?",
    answer:
      "Yes. DeFiMatrix combines: Audited Smart Contracts (CertiK & Hacken verified), Real-Time AI Monitoring (Anomaly detection), User-Controlled Assets (No custody)",
  },
  // More questions...
];
const multichains = [
  {
    question: "Why does DeFiMatrix use AI-powered multi-chain strategies?",
    answer:
      "Our AI agent scans 50+ blockchains in real-time, automatically allocating your funds to the highest-yielding opportunities while managing cross-chain complexity for you. No manual research or bridging required. Key AI Features: Automatic chain selection (Based on APY, gas fees, and risk), Self-optimizing portfolios (Continuous rebalancing)",
  },
  {
    question: "Which assets can the AI agent manage?",
    answer:
      "DeFiMatrix's AI supports 100+ tokens across EVM chains. Our agent evaluates each asset's yield potential and safety parameters before auto-compounding your earnings. Autonomous Management Includes: ✓ Stablecoins ✓ Blue-chip DeFi tokens ✓ Liquid staking tokens",
  },
  {
    question: "How do I set up an AI strategy?",
    answer:
      "Tell the AI your goal (e.g., “Maximize stablecoin yield with medium risk”) → Approve the agent's plan (See protocol whitelist and simulated returns) → Let the AI work (24/7 monitoring + automatic adjustments) AI Advantages: No manual comparisons - The agent handles research One-time setup - Earns while you sleep",
  },
  // More questions...
];
const earnings = [
  {
    question: "How does the AI calculate and optimize APY?",
    answer:
      "Our autonomous agent continuously analyzes 100+ factors across protocols - including compounding frequency, liquidity depth, and historical APY stability - to surface the most reliable yields. APY updates in real-time as the AI rebalances positions.AI-Powered Precision: Dynamic compounding (Auto-harvests & reinvests at optimal intervals), Risk-adjusted yields (Avoids high APYs with unsustainable mechanisms)",
  },
  {
    question: "When can I withdraw my funds?",
    answer:
      "Your AI-managed vault operates 24/7 with no fixed lock-ups. Request withdrawals anytime, and the agent will: Automatically unwind positions - Minimize slippage via aggregated DEX liquidity - Process in <2 mins for stablecoins Autonomy Benefits: ✓ No manual unwinding of complex positions ✓ Cross-protocol withdrawals in one click",
  },
  {
    question: "Are there any fees associated with using DeFiMatrix?",
    answer:
      "*DeFiMatrix uses a transparent performance-only fee model: 0% deposit/withdrawal fees, 10% fee only on profits generated by the AI. Fee Automation: Smart contracts auto-calculate fees, Real-time tracking in your dashboard",
  },
  // More questions...
];
const technicals = [
  {
    question: "What should I do if I encounter an issue?",
    answer:
      "Our support team is available 24/7 via the help section on our website, ready to assist with any technical concerns or inquiries you might have.",
  },
  {
    question: "Can I access DeFiMatrix on my mobile device?",
    answer:
      "Yes, DeFiMatrix is designed for accessibility, allowing you to manage your savings conveniently on both desktop and mobile platforms.",
  },
  // More questions...
];
const futures = [
  {
    question: "Will DeFiMatrix introduce more cryptocurrencies?",
    answer:
      "We are constantly assessing and incorporating new cryptocurrencies into our platform, guided by market demand, trends, and stringent security and performance standards.",
  },
  {
    question: "Are there plans to expand DeFiMatrix's features?",
    answer:
      "Definitely! Innovation is at the heart of DeFiMatrix. We are dedicated to introducing new features and saving options to enhance your experience and optimize your earning potential.",
  },
  // More questions...
];

export default function Faqs() {
  return (
    <div className="bg-black">
      <div id="faqs" className="container relative z-50 mx-auto 2xl:max-w-screen-2xl pt-12 md:pt-16">
        <div className="mx-auto max-w-6xl px-4 py-16 lg:px-8 2xl:max-w-7xl">
          <div className="mx-auto mb-14 w-auto text-center">
            <img className="inline-block animate-pulse" src="/images/slider-element.svg" alt="" />
          </div>
          <div className="absolute left-0 right-0 top-80 -z-10 mx-auto flex w-full items-center justify-center">
            <img src="/images/circle-bg.svg" alt="" />
            <img src="/images/gradient-bg.svg" className="absolute animate-pulse opacity-30 blur-3xl" alt="" />
          </div>
          <div className="lg:grid lg:grid-cols-12 lg:gap-8">
            <div className="lg:col-span-5">
              <h2 className="text-3xl font-bold leading-10 tracking-tight text-white">
                FAQs - Your Questions, Answered
              </h2>
              <p className="mt-4 text-base leading-7 text-gray-200">
                Can&apos;t find the answer you&apos;re looking for? Reach out to our{" "}
                <a href="mailto:support@defimatrix.io" className="font-semibold text-[#C450D5] hover:text-[#C450D5]">
                  customer support
                </a>{" "}
                team.
              </p>
            </div>
            <div className="mt-10 lg:col-span-7 lg:mt-0">
              <Tab.Group>
                <Tab.List className="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
                  <Tab
                    className={({ selected }) =>
                      classNames(
                        "inline-flex items-center justify-center rounded-full bg-white/10 px-4 py-2 text-center text-sm font-medium leading-5",
                        "focus:outline-none ",
                        selected
                          ? " border border-[#C450D5] !bg-black text-white shadow hover:bg-white/10"
                          : "text-blue-100 hover:bg-white/10 hover:text-white",
                      )
                    }
                  >
                    General Questions
                  </Tab>
                  <Tab
                    className={({ selected }) =>
                      classNames(
                        "inline-flex items-center justify-center rounded-full bg-white/10 px-4 py-2 text-center text-sm font-medium leading-5",
                        "focus:outline-none ",
                        selected
                          ? " border border-[#C450D5] !bg-black text-white shadow hover:bg-white/10"
                          : "text-blue-100 hover:bg-white/10 hover:text-white",
                      )
                    }
                  >
                    Multi-Chain, Multi-Token Approach
                  </Tab>
                  <Tab
                    className={({ selected }) =>
                      classNames(
                        "inline-flex items-center justify-center rounded-full bg-white/10 px-4 py-2 text-center text-sm font-medium leading-5",
                        "focus:outline-none ",
                        selected
                          ? " border border-[#C450D5] !bg-black text-white shadow hover:bg-white/10"
                          : "text-blue-100 hover:bg-white/10 hover:text-white",
                      )
                    }
                  >
                    Earnings and Withdrawals
                  </Tab>
                  <Tab
                    className={({ selected }) =>
                      classNames(
                        "inline-flex items-center justify-center rounded-full bg-white/10 px-4 py-2 text-center text-sm font-medium leading-5",
                        "focus:outline-none ",
                        selected
                          ? " border border-[#C450D5] !bg-black text-white shadow hover:bg-white/10"
                          : "text-blue-100 hover:bg-white/10 hover:text-white",
                      )
                    }
                  >
                    Technical Support
                  </Tab>
                  <Tab
                    className={({ selected }) =>
                      classNames(
                        "inline-flex items-center justify-center rounded-full bg-white/10 px-4 py-2 text-center text-sm font-medium leading-5",
                        "focus:outline-none ",
                        selected
                          ? " border border-purple-700 !bg-black text-white shadow hover:bg-white/10"
                          : "text-blue-100 hover:bg-white/10 hover:text-white",
                      )
                    }
                  >
                    Future Developments
                  </Tab>
                </Tab.List>
                <Tab.Panels>
                  <Tab.Panel>
                    <dl className="space-y-1">
                      {generals.map((general) => (
                        <Disclosure as="div" key={general.question} className="pt-4">
                          {({ open }) => (
                            <>
                              <div
                                className={`p-4 ${open ? "bg-[#252134]" : "bg-black"} rounded-lg border border-white/10`}
                              >
                                <dt>
                                  <Disclosure.Button className="flex w-full items-start justify-between text-left text-white">
                                    <span className="text-sm font-semibold leading-7 sm:text-base">
                                      {general.question}
                                    </span>
                                    <span className="ml-6 flex h-7 items-center">
                                      {open ? (
                                        <MinusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      ) : (
                                        <PlusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      )}
                                    </span>
                                  </Disclosure.Button>
                                </dt>
                                <Disclosure.Panel as="dd" className="mt-2 pr-12">
                                  <p className="text-base leading-7 text-gray-300">{general.answer}</p>
                                </Disclosure.Panel>
                              </div>
                            </>
                          )}
                        </Disclosure>
                      ))}
                    </dl>
                  </Tab.Panel>
                  <Tab.Panel>
                    <dl className="space-y-1">
                      {multichains.map((multichain) => (
                        <Disclosure as="div" key={multichain.question} className="pt-4">
                          {({ open }) => (
                            <>
                              <div
                                className={`p-4 ${open ? "bg-[#252134]" : "bg-black"} rounded-lg border border-white/10`}
                              >
                                <dt>
                                  <Disclosure.Button className="flex w-full items-start justify-between text-left text-white">
                                    <span className="text-sm font-semibold leading-7 sm:text-base">
                                      {multichain.question}
                                    </span>
                                    <span className="ml-6 flex h-7 items-center">
                                      {open ? (
                                        <MinusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      ) : (
                                        <PlusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      )}
                                    </span>
                                  </Disclosure.Button>
                                </dt>
                                <Disclosure.Panel as="dd" className="mt-2 pr-12">
                                  <p className="text-base leading-7 text-gray-300">{multichain.answer}</p>
                                </Disclosure.Panel>
                              </div>
                            </>
                          )}
                        </Disclosure>
                      ))}
                    </dl>
                  </Tab.Panel>
                  <Tab.Panel>
                    <dl className="space-y-1">
                      {earnings.map((earning) => (
                        <Disclosure as="div" key={earning.question} className="pt-4">
                          {({ open }) => (
                            <>
                              <div
                                className={`p-4 ${open ? "bg-[#252134]" : "bg-black"} rounded-lg border border-white/10`}
                              >
                                <dt>
                                  <Disclosure.Button className="flex w-full items-start justify-between text-left text-white">
                                    <span className="text-sm font-semibold leading-7 sm:text-base">
                                      {earning.question}
                                    </span>
                                    <span className="ml-6 flex h-7 items-center">
                                      {open ? (
                                        <MinusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      ) : (
                                        <PlusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      )}
                                    </span>
                                  </Disclosure.Button>
                                </dt>
                                <Disclosure.Panel as="dd" className="mt-2 pr-12">
                                  <p className="text-base leading-7 text-gray-300">{earning.answer}</p>
                                </Disclosure.Panel>
                              </div>
                            </>
                          )}
                        </Disclosure>
                      ))}
                    </dl>
                  </Tab.Panel>
                  <Tab.Panel>
                    <dl className="space-y-1">
                      {technicals.map((technical) => (
                        <Disclosure as="div" key={technical.question} className="pt-4">
                          {({ open }) => (
                            <>
                              <div
                                className={`p-4 ${open ? "bg-[#252134]" : "bg-black"} rounded-lg border border-white/10`}
                              >
                                <dt>
                                  <Disclosure.Button className="flex w-full items-start justify-between text-left text-white">
                                    <span className="text-sm font-semibold leading-7 sm:text-base">
                                      {technical.question}
                                    </span>
                                    <span className="ml-6 flex h-7 items-center">
                                      {open ? (
                                        <MinusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      ) : (
                                        <PlusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      )}
                                    </span>
                                  </Disclosure.Button>
                                </dt>
                                <Disclosure.Panel as="dd" className="mt-2 pr-12">
                                  <p className="text-base leading-7 text-gray-300">{technical.answer}</p>
                                </Disclosure.Panel>
                              </div>
                            </>
                          )}
                        </Disclosure>
                      ))}
                    </dl>
                  </Tab.Panel>
                  <Tab.Panel>
                    <dl className="space-y-1">
                      {futures.map((future) => (
                        <Disclosure as="div" key={future.question} className="pt-4">
                          {({ open }) => (
                            <>
                              <div
                                className={`p-4 ${open ? "bg-[#252134]" : "bg-black"} rounded-lg border border-white/10`}
                              >
                                <dt>
                                  <Disclosure.Button className="flex w-full items-start justify-between text-left text-white">
                                    <span className="text-sm font-semibold leading-7 sm:text-base">
                                      {future.question}
                                    </span>
                                    <span className="ml-6 flex h-7 items-center">
                                      {open ? (
                                        <MinusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      ) : (
                                        <PlusSmallIcon className="h-6 w-6" aria-hidden="true" />
                                      )}
                                    </span>
                                  </Disclosure.Button>
                                </dt>
                                <Disclosure.Panel as="dd" className="mt-2 pr-12">
                                  <p className="text-base leading-7 text-gray-300">{future.answer}</p>
                                </Disclosure.Panel>
                              </div>
                            </>
                          )}
                        </Disclosure>
                      ))}
                    </dl>
                  </Tab.Panel>
                </Tab.Panels>
              </Tab.Group>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
